Autosave Feature
stefanw/channels-yroom pull request #14
Opened 2023-09-08 15:51 UTC by atheler

Implementing autosave functionality which snapshots a room after a period of editing inactivity.

**Motivation**

A collaborative document gets stored in a database with additional versioning. It would be nice if the stored snapshots correspond to a *stable* state of the document. That is, in between edits.

**Changes**

A new `AUTOSAVE_DELAY` setting was added which controls the debounce delay per room. This is turned off by default.

`YROOM_SETTINGS = {'my-document': {'AUTOSAVE_DELAY': 10.0}}`

An additional [`Autosave`](https://github.com/atheler/channels-yroom/blob/c1ff4b157eac038b9c3a0f45a548ee6101224413/channels_yroom/autosave.py#L21C11-L21C11) object inside the `YRoomChannelConsumer` handles the debouncing and triggers the snapshots. This object spawns a waiter task for each room similar to the cleanup tasks of `YRoomChannelConsumer`.

**Issue / Open Question**

In order for this to work proper editing messages need to be distinguished from awareness / background messages. Unfortunately I am not familiar enough with the `lib0 encoding` scheme. For now a simple size threshold is in place inside [Autosave.nudge_if_changed()](https://github.com/atheler/channels-yroom/blob/c1ff4b157eac038b9c3a0f45a548ee6101224413/channels_yroom/autosave.py#L67-L73). This needs refinement and I would be grateful for inputs pointing me in the right direction.

**Closing**

Let me know what you think and thanks again to @stefanw for the great work!

2023-09-10 20:14 UTC, stefanw requested changes
Feel free to open a PR in `yroom` to create `has_edits` flag but I can also have a look.

2023-09-10 20:14 UTC, stefanw commented on channels_yroom/autosave.py
> +        # TODO: There must be a better way?!
It looks like it would be helpful to expose some flag on `YRoomMessage` (not `YroomChannelMessage` but the result of `handle_message`) that indicates editing has happened? I can implement that in [`yroom`](https://github.com/stefanw/yroom/).

2023-09-10 20:14 UTC, stefanw commented on channels_yroom/autosave.py
> +    def nudge_if_changed(self, room_message: str, message: YroomChannelMessage) -> None:
`room_message` should rather be `room_name`.

2023-09-10 20:14 UTC, stefanw commented on channels_yroom/channel.py
> +        self.autosave.nudge_if_changed(room_name, message)
Here `result` could contain a flag that indicates changes have been applied that require persisting.

2023-09-10 20:14 UTC, stefanw commented on channels_yroom/channel.py
> +        self.autosave.forget(room_name)
Should this be in `remove_room` when the room is actually removed? Here the scheduled removal can still be canceled when the room becomes alive again. But I guess it makes sense here so that auto save and "remove room" delay don't both race to do a snapshot?

2023-09-11 07:10 UTC, atheler commented on channels_yroom/autosave.py
> +    def nudge_if_changed(self, room_message: str, message: YroomChannelMessage) -> None:
Thanks for the hint! Changed in 061db29

2023-09-11 07:21 UTC, atheler commented on channels_yroom/channel.py
> +        self.autosave.forget(room_name)
Yes that was the idea (no duplicate race saving). But now I think I did not consider the following edge case: There is a pending auto save -> room becomes empty -> room becomes alive again and now we effectively lost an auto save. So it seems indeed better to move the `autosave.forget(room_name)` inside of `YRoomChannelConsumer.remove_room`?

2023-09-11 07:29 UTC, atheler commented on channels_yroom/autosave.py
> +        # TODO: There must be a better way?!
That would probably be the cleanest way. I think by naming it `has_edits` it should also be clear that it is about `data` and not `awareness` changes.

2023-09-11 07:34 UTC, atheler commented on channels_yroom/channel.py
> +        self.autosave.nudge_if_changed(room_name, message)
With a `result.has_edits` flag I think we could scrap the `nudge_if_changed` method and replace the coupling with 

```python
if result.has_edits:
    self.autosave.nudge(room_name)
```

This way Autosave doesn't have to know about any messages.

2023-09-11 07:56 UTC, atheler commented on channels_yroom/autosave.py
> +        # TODO: There must be a better way?!
Had a quick look into [yroom](https://github.com/stefanw/yroom/). Would this extension boil down to?
- Adding `has_edits` flag to `YRoomMessage`
- Inside `YRoom.handle_message()` declaring `let mut has_edits = false;` and
  setting it to `true` during the `Message::Sync(SyncMessage::Update(data)) => {...}`
  match
- Adding `has_edits` argument to the `YRoomMessage.from_payloads()` constructor

I could give it a shot but sadly I have never done anything with Rust.

2023-09-11 08:12 UTC, stefanw commented on channels_yroom/autosave.py
> +        # TODO: There must be a better way?!
The yroom plan sounds good to me. Don't forget to adjust the typing in the `pyi` file. Try it, if you run into trouble, let me know.

2023-09-15 15:49 UTC, atheler commented
I updated the code for the use of the new `YRoomMessage.has_edits` flag from [Adding has_edits Flag to YRoomMessage](https://github.com/stefanw/yroom/pull/2). The changes seem to work nicely together inside my current Django application and the unnecessary autosaves disappeared.

2023-10-05 15:39 UTC, atheler commented
Why was the forward reference to `YRoomChannelConsumer` removed?

2023-11-10 09:48 UTC, stefanw approved these changes

2023-11-10 09:53 UTC, stefanw commented
> Why was the forward reference to YRoomChannelConsumer removed?
Sorry, bad rebase when I tried to fix the style of the forward ref (`black` didn't like it).

2023-11-10 09:56 UTC, merged